name: Automacao Reporte Shopee

on:
  workflow_dispatch:

jobs:
  executar-script:
    runs-on: ubuntu-latest
    
    # Define o fuso horário para todo o ambiente de execução
    env:
      TZ: America/Sao_Paulo

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar bibliotecas (requirements.txt)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar o Script de Automação
      env:
        # Puxa o segredo exato que você criou nas configurações do repositório
        COOKIES_SESSAO: ${{ secrets.COOKIES_SESSAO }} 
      run: python script.py

    - name: Salvar os Prints como Arquivo (Artefato)
      uses: actions/upload-artifact@v4
      if: always() # Salva o print mesmo que o script dê erro
      with:
        name: prints-da-automacao
        path: "*.png"
